#server:
#  port: 8000
#
#zuul:
#  ignoredServices: '*'
#  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#  prefix: /api
#  routes:
#    organizations:
#      path: /organizations/**
#      serviceId: organization-service
#      strip-prefix: false
#    departments:
#      path: /departments/**
#      serviceId: department-service
#      strip-prefix: false
#    employees:
#      path: /employees/**
#      serviceId: employee-service
#      strip-prefix: false
#    
#
#endpoints:
#  routes:
#    sensitive: false
#  trace:
#    sensitive: false
#
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
